FROM nginx:mainline-alpine
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

ARG APPDIR="/var/www/html"
RUN mkdir -p ${APPDIR}

COPY ./front/dist ${APPDIR}

#ARG APP_USER="nginx"
#RUN apt-get update && useradd -rM -s /bin/bash ${APPUSER}


RUN apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    apk del tzdata

EXPOSE 80

USER ${APP_USER}

CMD ["nginx", "-g", "daemon off;"]
