# Generated by Django 3.0.8 on 2020-08-19 10:38

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('place_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('business_status', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('formatted_address', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('user_ratings_total', models.IntegerField()),
                ('photos', jsonfield.fields.JSONField(null=True)),
                ('geometry', jsonfield.fields.JSONField(null=True)),
                ('types', jsonfield.fields.JSONField(null=True)),
            ],
        ),
    ]
