# Generated by Django 3.1 on 2020-08-20 09:33

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('photos', jsonfield.fields.JSONField(null=True)),
                ('reviews', jsonfield.fields.JSONField(null=True)),
                ('opening_hours', jsonfield.fields.JSONField(null=True)),
                ('address_components', jsonfield.fields.JSONField(null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.places')),
            ],
        ),
    ]
